### ISSUE TITLE
function called during library load

### ISSUE THREAD

**Issue by lazatsoc** [yugr/Implib.so#15]
Hi, many thanks for this useful tool, it seems like it will facilitate our job a lot!

However, I have a problem using it: 

I have used implib-gen on a dynamic library like this:

`../implib-gen.py libnvinfer.so.6.5.0`

When loading the library I get the following error:

`implib-gen: libnvinfer.so.6.5.0: library function '_ZN8nvinfer16LogBufC1EPNS_7ILoggerENS1_8SeverityEm' called during library load`

With my limited knowledge, I cannot understand what this error means.
Is a default constructor of a class (Logger) being called upon loading?

I have also tried to disable lazy loading but still the same error.

What would be the next steps in investigating it?

Thanks.

**Comment by yugr** [comment]
Thank you for using Implib.so.

Yes, it looks like the error is caused by a C++ constructor which calls one of the library functions. It's a chicken and egg problem: Implib.so can not intercept `_ZN8nvinfer16LogBufC1EPNS_7ILoggerENS1_8SeverityEm` until the library is loaded (via `dlopen`) but `dlopen` can not finish until library constructors have completed (for which it needs all functions to be intercepted...).

Quick experiment shows that there is a workaround for this behavior (querying not-yet-fully-loaded library with `RTLD_NOLOAD` flag when we run into this error) but it will not work transparently for all the use-cases e.g. not when user provides a custom callback to load the library.

This is a nasty situation, let me think it over.

**Comment by yugr** [comment]
BTW I assume everything will work if you compile generated code with `-DIMPLIB_HIDDEN_SHIMS`?

**Comment by lazatsoc** [comment]
Yes it works perfectly with `-DIMPLIB_HIDDEN_SHIMS`.

Thank you very much!

**Comment by yugr** [comment]
Ah, good. I guess I'll enable this option by default then.

**Comment by lazatsoc** [comment]
So, what does this option mean exactly?  Is it that the symbols of this library will be hidden and won't be able to be called externally?

**Comment by yugr** [comment]
> So, what does this option mean exactly? Is it that the symbols of this library will be hidden
> and won't be able to be called externally?

Basically yes. Without this macro the generated wrappers (e.g. for `_ZN8nvinfer16LogBufC1EPNS_7ILoggerENS1_8SeverityEm`) will have public [visibility](https://www.ibm.com/docs/en/ztpf/1.1.0.15?topic=linkage-visibility-in-shared-objects) i.e. will be exported from your library.

> In our case, we are creating a library that will depend on libnvinfer.so.6.5.0. And we don't want to expose libnvinfer.so.6.5.0 to the rest of the code that will depend on our library.

Yes and I think same applies to majority of users. People generally will not want to make wrappers public as this would pollute interface of their libraries with external symbols. So I think wrappers should be hidden by default. I already have a patch for this which I plan to commit later today.

**Comment by yugr** [comment]
Shim symbols are now hidden by default so `-DIMPLIB_HIDDEN_SHIMS` is no longer needed. Let me know if you have other issues.
