### ISSUE TITLE
Support for exported variables

### ISSUE THREAD

**Issue by ilya-fedin** [yugr/Implib.so#30]
I don't know how much it is in scope or how it's simple to implement but libX11 seem to export a lot of variables and it's not really possible to make it optional using Implib right now.

**Comment by yugr** [comment]
Unfortunately supporting variables is problematic because they may contain target-specific relocations which will need to be replicated in shim code. This is a lot of work.

Another problem is that library may internally reference it's own variables via private aliases so the overloaded copies in shim will not be used.

**Comment by yugr** [comment]
This is a known limitation of Implib.so. I have no plans to work on this atm.
